#!/usr/bin/env python3
"""Create small, fictional inputs for the public smoke test and Quick Start."""

from __future__ import annotations

import argparse
import csv
import json
import zipfile
from pathlib import Path

import numpy as np
from biom import Table


FEATURES = [f"F{index:02d}" for index in range(1, 13)]
BASE_SEQUENCES = {
    "A": "ACGTACGTACGTACGT",
    "B": "TGCATGCATGCATGCA",
    "C": "AACCAACCAACCAACC",
}
TAXONOMY = {
    "A": ("Bacteria", "Firmicutes", "Bacilli", "OrderA", "FamilyA", "GenusA", "SpeciesA"),
    "B": ("Bacteria", "Proteobacteria", "Gammaproteobacteria", "OrderB", "FamilyB", "GenusB", "SpeciesB"),
    "C": ("Bacteria", "Actinobacteriota", "Actinomycetia", "OrderC", "FamilyC", "GenusC", "SpeciesC"),
}


def write_biom(path: Path, sample_ids: list[str], labels: list[str]) -> None:
    matrix = np.full((len(FEATURES), len(sample_ids)), 20.0, dtype=float)
    for column, label in enumerate(labels):
        group = ord(label) - ord("A")
        matrix[group * 4:(group + 1) * 4, column] += 300.0
    table = Table(matrix, FEATURES, sample_ids, type="OTU table")
    path.write_text(table.to_json("multi-variant-classification synthetic example"))


def write_qza(path: Path) -> None:
    fasta = "".join(f">{feature}\n{BASE_SEQUENCES[chr(ord('A') + index % 3)]}\n" for index, feature in enumerate(FEATURES))
    with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("synthetic/data/dna-sequences.fasta", fasta)


def write_marine(path: Path) -> None:
    fields = [
        "sample", "geo_loc_name", "ASV_sequence", "domain", "phylum", "class",
        "order", "family", "genus", "species",
    ]
    rows = []
    for index in range(30):
        label = chr(ord("A") + index % 3)
        taxonomy = TAXONOMY[label]
        for feature_index in range(3):
            sequence = BASE_SEQUENCES[label] + "ACGT" * feature_index
            rows.append({
                "sample": f"marine_sample_{index:02d}",
                "geo_loc_name": f"Synthetic location {label}",
                "ASV_sequence": sequence,
                **dict(zip(fields[3:], taxonomy, strict=True)),
            })
    with path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def write_emp(outdir: Path) -> None:
    sample_ids = [f"emp_sample_{index:02d}" for index in range(30)]
    labels = [chr(ord("A") + index % 3) for index in range(30)]
    write_biom(outdir / "emp_feature_table.biom", sample_ids, labels)
    with (outdir / "emp_metadata.tsv").open("w", newline="") as handle:
        writer = csv.writer(handle, delimiter="\t")
        writer.writerow(["#SampleID", "empo_1", "empo_2", "empo_3"])
        for sample, label in zip(sample_ids, labels, strict=True):
            writer.writerow([sample, f"EMPO1-{label}", f"EMPO2-{label}", f"EMPO3-{label}"])


def write_hmtol(outdir: Path) -> None:
    pre_ids = [f"hmtol_sample_{index:02d}" for index in range(30)]
    pre_labels = [chr(ord("A") + index % 3) for index in range(30)]
    write_biom(outdir / "hmtol_before_qc" / "feature-table.biom", pre_ids, pre_labels)
    with (outdir / "hmtol_before_qc" / "metadata.tsv").open("w", newline="") as handle:
        writer = csv.writer(handle, delimiter="\t")
        writer.writerow(["SampleID", "Country"])
        for sample, label in zip(pre_ids, pre_labels, strict=True):
            writer.writerow([sample, f"Synthetic country {label}"])

    qc_ids = [f"qc_sample_{index:02d}" for index in range(36)]
    qc_labels = [chr(ord("A") + index % 3) for index in range(36)]
    write_biom(outdir / "hmtol_qc" / "feature-table.qc.min3.biom", qc_ids, qc_labels)
    with (outdir / "hmtol_qc" / "metadata.qc.min3.tsv").open("w", newline="") as handle:
        writer = csv.writer(handle, delimiter="\t")
        writer.writerow(["SampleID", "study", "Continent", "region"])
        for index, (sample, label) in enumerate(zip(qc_ids, qc_labels, strict=True)):
            writer.writerow([
                sample,
                f"synthetic_study_{index // 6:02d}",
                f"Synthetic continent {label}",
                f"Synthetic region {label}",
            ])
    write_qza(outdir / "synthetic-sequences.qza")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--outdir", type=Path, default=Path("examples/data"))
    args = parser.parse_args()
    args.outdir.mkdir(parents=True, exist_ok=True)
    (args.outdir / "hmtol_before_qc").mkdir(exist_ok=True)
    (args.outdir / "hmtol_qc").mkdir(exist_ok=True)
    write_marine(args.outdir / "marine_edna.csv")
    write_emp(args.outdir)
    write_hmtol(args.outdir)
    (args.outdir / "README.txt").write_text(
        "Fictional, release-safe data generated by generate_synthetic_data.py.\n"
    )
    print(json.dumps({"output": str(args.outdir.resolve()), "features": len(FEATURES)}, indent=2))


if __name__ == "__main__":
    main()
